server:
 port: 9001 #端口
spring:
 application:
  name: activemq-producer # 服务名称
# springboot与activemq整合配置
 activemq:
  broker-url: tcp://192.168.175.132:61616 # 连接地址
  user: admin # activemq用户名
  assword: admin # activemq密码
# 指定发送模式 （点对点 false ， 发布订阅 true）
 jms:
  pub-sub-domain: true


